### ISSUE TITLE
rust-lang/libc builds are timing out

### ISSUE THREAD

**Issue by gnzlbg** [cirruslabs/cirrus-ci-web#105] opened 2019-08-08 17:14 UTC
For example, see here: https://cirrus-ci.com/build/5121064810577920

It appears that the builds start executing, but never finish, and I can't access any logs. They usually finish in ~4min.

**Comment by RDIL** [comment] 2019-08-08 17:15
Hey @gnzlbg!

Sadly, we are having Kubernetes cluster issues. I'm not sure when it will be fixed. They are working on it though.

**Comment by gnzlbg** [comment] 2019-08-08 17:16
Roger that, thank you for the quick reply. 

I've canceled the builds. Could you let us know when the issues are resolved so that we can retry ?

**Comment by RDIL** [comment] 2019-08-08 17:16
I'll ping you once everything is back online :)

**Comment by RDIL** [comment] 2019-08-08 17:31
@gnzlbg see #414

**Comment by fkorotkov** [comment] 2019-08-08 17:48
The issue is resolved now

**Closed by fkorotkov** 2019-08-08 17:48 UTC

**Comment by gnzlbg** [comment] 2019-08-08 18:30
Thank you!
