### ISSUE TITLE
Prioritize a specific task

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/cirrus-ci-web#450] opened 2022-07-21 09:20 UTC
A possibility to move a specific queued task (or some tasks) to the front of the queue will be very helpful from time to time. For example, when you made a PR that fixes an issue on MacOS but all the MacOS builds come last in the queue.

**Comment by fkorotkov** [comment] 2022-07-21 09:23
Duplicate of https://github.com/cirruslabs/cirrus-ci-docs/issues/525

**Closed by fkorotkov** 2022-07-21 09:23 UTC

**Comment by real-or-random** [comment] 2022-07-21 10:10
Ah nice! Though I don't think it's a 100% duplicate. I was not thinking about a config option but rather about some button in the web interface, to move a task only once.
