### ISSUE TITLE
Web terminal unusable on macOS 10.11.6/Chrome (was: " on FreeBSD)

### ISSUE THREAD

**Issue by phil-blain** [cirruslabs/cirrus-ci-web#446] opened 2022-05-10 12:29 UTC
Hi,

I tried the web terminal for the first time on FreeBSD, and the text is all garbled, the cursor is all over the place... Here is a screen shot from a file open in Vi, you can see there are like a dozen cursor character, and the listing from the `ls` I did before opening the file is visible on half the screen.

![Capture d’écran 2022-05-10 à 08 28 14](https://user-images.githubusercontent.com/44212482/167628338-50e02fe9-4a63-4df5-ab39-a46881d0a422.png)

**Comment by edigaryev** [comment] 2022-05-15 18:38
The terminal seems to be working fine for me on `13.0-RELEASE` and latest Chrome on macOS:

<img width="1172" alt="Screenshot 2022-05-15 at 21 36 16" src="https://user-images.githubusercontent.com/85709/168488604-ba846227-2c61-4e5f-a82c-947b13db372a.png">

Can you share your setup and some steps to reproduce the issue you're facing?

**Comment by edigaryev** [comment] 2022-05-20 11:34
Closing because i doesn't seem to reproduce in Firefox 100 either:

<img width="1172" alt="Screenshot 2022-05-20 at 14 32 49" src="https://user-images.githubusercontent.com/85709/169519984-4c3d2a59-db10-401e-8be6-7e902a5d5466.png">

Nor in the latest Safari.

Please reply with your setup details/steps to reproduce if this is still happening for you.

**Comment by phil-blain** [comment] 2022-05-20 13:04
Hi ! Sorry for not getting back to you sooner.

I'm experiencing this on latest Chrome on macOS. An example of a build is: https://cirrus-ci.com/task/4597971764379648.

This is the CI build for Git. Here is what I have in `.cirrus.yml`:
(https://github.com/phil-blain/git/blob/cirrus-freebsd-git-send-email/.cirrus.yml)
~~~yaml
env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  env:
    GIT_PROVE_OPTS: "--timer --jobs 10"
    GIT_TEST_OPTS: "--no-chain-lint --no-bin-wrappers"
    MAKEFLAGS: "-j4"
    DEFAULT_TEST_TARGET: prove
    DEVELOPER: 1
  freebsd_instance:
    image_family: freebsd-13-0
    memory: 2G
  install_script:
    pkg install -y gettext gmake perl5 vim
  create_user_script:
    - pw useradd git
    - chown -R git:git .
  build_script:
    - su git -c gmake
  test_script:
    - su git -c 'cd t && ./t9001-send-email.sh -dvx'
~~~

Originally we had `image_family: freebsd-12-2` but I just tried with `freebsd-13-0` and get the same behaviour. Please let me know if you can reproduce.

I could try to provide a screencast if it helps.

My steps:
1. Push to my branch (`cirrus-freebsd-git-send-email`) to my fork
2. Go to https://cirrus-ci.com/github/phil-blain/git/cirrus-freebsd-git-send-email, and wait for the new job to appear
3. Click on the job
4. Click on the `freebsd_12` task
5. Click cancel
6. Click on Rerun with Terminal access
7. Wait for the terminal
8. Interact with the terminal when it appears

Note that I am on macOS 10.11.6 so a little old, but I can't imagine this playing a role since I'm running the latest Chrome, but I could be wrong...

**Comment by edigaryev** [comment] 2022-05-20 13:14
Hello Philippe, thanks for the detailed steps!

However, it still doesn't seem to reproduce for me. Can you please try:

1. Attaching Cirrus Terminal to a non-FreeBSD task (just an [ordinary `container`](https://cirrus-ci.org/guide/linux/) will do) to see if the issue still persists and confirm it is FreeBSD-specific?
2. Running Chrome without plugins (or any other browser, e.g. Safari) to see if this issue is browser-specific?

Thanks!

**Comment by phil-blain** [comment] 2022-05-20 15:04
OK, so I tried:

- same workflow, in Firefox 78 ESR on same macOS system: the terminal works correctly
- same workflow, in Firefox 100, on Kubuntu 20.04: the terminal works correctly
- same workflow, in Chromium 101.0.4951.64 on Kubuntu 20.04: the terminal works correctly.
- this workflow:, i.e. Linux container:
~~~yaml
env:
  CIRRUS_CLONE_DEPTH: 1

container:
  image: gcc:latest
task:
  tests_script: make test
~~~

the terminal acts in the same weird and mostly unusable manner as I describe above.

So
1. it's not FreeBSD-specific
2. It seems specific to at least macOS 10.11.6 + Chrome

I understand if it's not a priority to fix this since macOS 10.11.6 is not supported anymore, and I do have a workaround since Firefox works. Thanks for pointing me in the right direction !

**Comment by edigaryev** [comment] 2022-05-21 13:32
@phil-blain we've just deployed a web UI with the new version of [Xterm.js](https://xtermjs.org/) that *might* contain some bugfixes for this issue you're facing. Can you check to see if there's any improvement?

**Comment by phil-blain** [comment] 2022-05-21 15:11
Thanks, I just tried it after refreshing, but I stil get the same behaviour (Chrome/macOS).

**Comment by edigaryev** [comment] 2022-05-22 11:51
Have you [tried running Chrome in a separate profile](https://superuser.com/questions/377186/how-do-i-start-chrome-using-a-specified-user-profile), to see whether it's not-default plugins and/or settings causing this?

Otherwise I don't think this can be resolved without getting an access to El Capitan machine. I've tried installing [El Capitan](https://support.apple.com/en-us/HT211683) on my Intel-based MacBook, but it doesn't seem to support newer Macs. Installing El Capitan in a VM works, but Chrome is unusable there probably due to lack of/improper GPU acceleration.

**Closed by edigaryev** 2022-05-22 11:51 UTC
